### ISSUE TITLE
Rust 1.65

### ISSUE THREAD

**Issue by NewtTheWolf** [qdm12/rustdevcontainer#19]
This Project is nice, but Sadly i cannot work with it, is it maybe possible to update the image to 1.65?

**Comment by qdm12** [comment]
Upgraded to 1.66.0 in 2e6d29fc17b27c53616f9848d11c24346e20878f 😉 

I'll do a release shortly but you can use the latest image for now.

**Comment by qdm12** [comment]
Released https://github.com/qdm12/rustdevcontainer/releases/tag/v0.7.0 with corresponding images `qmcgaw/rustdevcontainer:v0.7.0`, `qmcgaw/rustdevcontainer:v0.7.0-alpine` and `qmcgaw/rustdevcontainer:v0.7.0-debian`

**Comment by qdm12** [comment]
Also FYI you can build it yourself as long as you have `git` installed, specifying the rust version.

- For Alpine:

  ```sh
  docker build -t qmcgaw/rustdevcontainer -f alpine.Dockerfile --build-arg RUST_VERSION=1.66.0 https://github.com/qdm12/rustdevcontainer.git
  ```

- For Debian

  ```sh
  docker build -t qmcgaw/rustdevcontainer -f debian.Dockerfile --build-arg RUST_VERSION=1.66.0 https://github.com/qdm12/rustdevcontainer.git
  ```

You can also specify other build arguments, see the Dockerfile, for example [`RUST_ANALYZER_VERSION`](https://github.com/qdm12/rustdevcontainer/blob/ba0a87aadae68ad7a519190953476ea433be5ff2/alpine.Dockerfile#L51)
