### ISSUE TITLE
Debian based devcontainer

### ISSUE THREAD

**Issue by qdm12** [qdm12/rustdevcontainer#5]

**Comment by ianpurton** [comment]
I have the start of a debian dev container here https://github.com/ianpurton/development_environments/tree/master/new-rust-devcontainer

I ended up coming FROM rust:1.51-slim-buster as trying to install rust the normal way seemed to bloat up debian:slim.

The defintion of rust slim is here. https://github.com/rust-lang/docker-rust/blob/master/1.53.0/buster/slim/Dockerfile

**Comment by qdm12** [comment]
> I ended up coming FROM rust:1.51-slim-buster as trying to install rust the normal way seemed to bloat up debian:slim.

Thanks for the heads up, that definitely saves 400MB whoa, not sure why yet though...

With release v0.2.0 there are now `qmcgaw/rustdevcontainer:debian` and `qmcgaw/rustdevcontainer:v0.2.0-debian` images which *should* work, although I haven't tested them too much yet.

Also subsequent releases and image with tags `:latest` , `:debian` ~and `:alpine`~ are now cross built for `amd64` and `arm64`.
